language: php

php:
  - 7.0
  - 7.1

services:
  - memcached

before_install:
  - yes '' | pecl install apcu;

before_script:
  - phpenv config-add travis.ini

script: phpunit --verbose --debug --stderr --config phpunit.xml tests