language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer require phpunit/phpunit:^6.3.0
  - yes '' | pecl install -f apcu;

before_script:
  - phpenv config-add travis.ini

script: $COMPOSER_HOME/phpunit --verbose --debug --stderr --config phpunit.xml tests