language: php

php:
  - 7.0
  - 7.1

before_install:
  - yes '' | pecl install -f apcu;

before_script:
  - phpenv config-add travis.ini

script: phpunit --version --verbose --debug --stderr --config phpunit.xml tests